# Generated by Django 5.2.5 on 2025-10-16 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, help_text='Format: XXXX-XXXXX where XXXX is year created and XXXXX is random/indexed (e.g., 2024-12345)', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_student_id', message='Student ID must be in format XXXX-XXXXX where XXXX is year created and XXXXX is random/indexed (e.g., 2024-12345)', regex='^\\d{4}-\\d{5}$')]),
        ),
    ]
