# Generated by Django 5.2.5 on 2025-10-21 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='approved_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate', to='candidate_module.candidateapplication'),
        ),
    ]
