# Generated by Django 5.2.5 on 2025-10-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolelection',
            name='end_year',
            field=models.IntegerField(blank=True, help_text='End year for SY format (e.g., 2026 for SY 2025-2026)', null=True),
        ),
        migrations.AddField(
            model_name='schoolelection',
            name='start_year',
            field=models.IntegerField(blank=True, help_text='Start year for SY format (e.g., 2025 for SY 2025-2026)', null=True),
        ),
    ]
