"""
Django settings for E_Botar project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment detection
# Railway sets PORT, RAILWAY_ENVIRONMENT, or RAILWAY_PUBLIC_DOMAIN
IS_RAILWAY = (
    os.environ.get('RAILWAY_ENVIRONMENT') is not None or
    os.environ.get('RAILWAY') is not None or
    os.environ.get('PORT') is not None
)
IS_PRODUCTION = os.environ.get('DJANGO_ENV') == 'production' or IS_RAILWAY

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-c1q*9=76a^$y76$(ysi+m-s8b%*=rdfm8i3$yv-pwcsev$k)2c')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true' if IS_PRODUCTION else True

# ALLOWED_HOSTS configuration
if IS_RAILWAY:
    # Railway provides RAILWAY_PUBLIC_DOMAIN or uses PORT
    allowed_hosts = ['*']  # Allow all hosts on Railway by default
    railway_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')
    if railway_domain:
        allowed_hosts.append(railway_domain)
    # Add custom domain if set
    custom_domain = os.environ.get('CUSTOM_DOMAIN', '')
    if custom_domain:
        allowed_hosts.append(custom_domain)
    # Also check for explicit ALLOWED_HOSTS env var
    explicit_hosts = os.environ.get('ALLOWED_HOSTS', '')
    if explicit_hosts:
        allowed_hosts.extend([h.strip() for h in explicit_hosts.split(',') if h.strip()])
    ALLOWED_HOSTS = allowed_hosts
else:
    ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # Django Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # 'allauth.socialaccount.providers.google',  # Disabled - Google OAuth not in use
    # Restructured apps (Phase 2)
    'auth_module',          # replaces 'users'
    'candidate_module',     # replaces 'candidates'
    'election_module',      # replaces 'election_management'
    'voting_module',        # replaces 'votes'
    'admin_module',         # replaces 'custom_admin'
    'security_module',
    'result_module',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files efficiently
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'E_Botar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'Template',  # Project-level templates organized by app: Template/<app_name>/...
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'E_Botar.context_processors.applications_status',  # Check if applications are available
            ],
        },
    },
]

WSGI_APPLICATION = 'E_Botar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PostgreSQL on Railway, SQLite for local development
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Parse DATABASE_URL (Railway format: postgresql://user:password@host:port/dbname)
    parsed = urlparse(DATABASE_URL)
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed.path[1:],  # Remove leading '/'
            'USER': parsed.username,
            'PASSWORD': parsed.password,
            'HOST': parsed.hostname,
            'PORT': parsed.port or '5432',
            'OPTIONS': {
                'sslmode': 'require',
            },
        }
    }
else:
    # Local development - use SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Project-level static organized by app: static/<app_name>/...
]

# WhiteNoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security settings for production
if IS_PRODUCTION:
    # HTTPS settings
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # HSTS settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# CSRF trusted origins for Railway
if IS_RAILWAY:
    railway_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')
    custom_domain = os.environ.get('CUSTOM_DOMAIN', '')
    csrf_origins = []
    if railway_domain:
        csrf_origins.append(f'https://{railway_domain}')
        csrf_origins.append(f'http://{railway_domain}')  # Also allow HTTP for Railway's internal routing
    if custom_domain:
        csrf_origins.append(f'https://{custom_domain}')
        csrf_origins.append(f'http://{custom_domain}')
    # If domains are available, set CSRF_TRUSTED_ORIGINS
    # If not set, Django will use the request's origin (works but less secure)
    if csrf_origins:
        CSRF_TRUSTED_ORIGINS = csrf_origins

# Authentication settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Django Allauth Settings
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth Configuration
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']  # email* makes email required (replaces deprecated ACCOUNT_EMAIL_REQUIRED)
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
# ACCOUNT_EMAIL_REQUIRED is deprecated - using email* in ACCOUNT_SIGNUP_FIELDS instead
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USER_MODEL_EMAIL_FIELD = 'email'

# Social Account Settings
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'mandatory'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_QUERY_EMAIL = True

# Google OAuth Settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}

# Google OAuth Credentials (Set these in environment variables for production)
# For now, Google OAuth is disabled but ready to be enabled
GOOGLE_OAUTH_ENABLED = False  # Set to True to enable Google OAuth
GOOGLE_OAUTH2_CLIENT_ID = 'your-google-client-id.apps.googleusercontent.com'
GOOGLE_OAUTH2_CLIENT_SECRET = 'your-google-client-secret'

# Custom User Profile Integration
SOCIALACCOUNT_ADAPTER = 'auth_module.adapters.CustomSocialAccountAdapter'
